server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.233.92.188:3306/dbcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 6+Wpsm-C+E/!3

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hp.entities
